e2e_docker_compose_enterprise_test:
    stage: BuildAndTest
    script:
        - sudo apt-get update
        - curl -sSL https://get.docker.com/ | sh #Install docker.
        # Install Docker Compose.
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
        - sudo docker-compose down -v
        # Install the cluster.
        - chmod +x ./env-setup.sh
        - ./env-setup.sh
        - npm run ci-docker-enterprise
        # Sleep for 5 mins to make sure docker started
        - sleep 5m
        # Set env var
        - export ACCOUNTS_URL=http://localhost:3003
        - export ADMIN_DASHBOARD_URL=http://localhost:3100
        - export DASHBOARD_URL=http://localhost:3000
        - export BACKEND_URL=http://localhost:3002
        - cd tests
        - npm install
        - npm run enterprise-test
        - cd ..
        - chmod +x ./ci/scripts/cleanup.sh
        - ./ci/scripts/cleanup.sh
    only:
        refs:
            - release
            - master
