{{- if .Values.haraka.domain -}}
############-----HARAKA----#############################
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ printf "%s-%s" $.Release.Name "haraka"  }}
    namespace: {{ $.Release.Namespace }}
    labels:
        app: {{ printf "%s-%s" $.Release.Name "haraka" }}
        app.kubernetes.io/part-of: oneuptime
        app.kubernetes.io/managed-by: Helm
spec:
    selector:
        matchLabels:
            app: {{ printf "%s-%s" $.Release.Name "haraka"  }}
    replicas: 1
    template:
        metadata:
            labels:
                app: {{ printf "%s-%s" $.Release.Name "haraka"  }}
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository "haraka" .Values.image.tag }}
                  name: {{ printf "%s-%s" $.Release.Name "haraka"  }}
                  imagePullPolicy: {{ $.Values.image.pullPolicy }}
                  resources:
                    requests:
                      cpu: 250m
                    limits:
                      cpu: 500m
                  env:
                      - name: SMTP_USER
                        value: {{ $.Values.haraka.user }}
                      - name: SMTP_PASSWORD
                        value: {{ $.Values.haraka.password }}
                      - name: DOMAIN
                        value: {{ $.Values.haraka.domain }}
                      - name: DKIM_PRIVATE_KEY
                        value: {{ $.Values.haraka.dkimPrivateKey }}
                      - name: TLS_CERT
                        value: {{ $.Values.haraka.tlsCert }}
                      - name: TLS_KEY
                        value: {{ $.Values.haraka.tlsKey }}
                      - name: NODE_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.nodeName
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_IP
                        valueFrom:
                          fieldRef:
                            fieldPath: status.podIP
                      - name: POD_SERVICE_ACCOUNT
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.serviceAccountName
                  ports:
                      - containerPort: {{ $.Values.host.harakaPort }}
                        hostPort: {{ $.Values.host.harakaPort }}
                        name: {{ printf "%s-%s" $.Release.Name "haraka"  }}
            restartPolicy: {{ $.Values.image.restartPolicy }}

---
# OneUptime Haraka Service
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ printf "%s-%s" $.Release.Name "haraka"  }}
        app.kubernetes.io/part-of: oneuptime
        app.kubernetes.io/managed-by: Helm
    name: {{ printf "%s-%s" $.Release.Name "haraka"  }}
    namespace: {{ $.Release.Namespace }}
spec:
    ports:
        - port: {{ $.Values.host.harakaServicePort }}
          targetPort: {{ $.Values.host.harakaPort }}
    selector:
        app: {{ printf "%s-%s" $.Release.Name "haraka"  }}
    type: ClusterIP
---
##########################################################
{{- end -}}

{{- if .Values.autoScaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" $.Release.Name "haraka"  }}
spec:
  maxReplicas: {{ $.Values.autoScaler.maxReplicas }}
  minReplicas: {{ $.Values.autoScaler.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" $.Release.Name "haraka"  }}
  targetCPUUtilizationPercentage: {{ $.Values.autoScaler.averageCpuUtilization }}
---
{{- end }}