###########-----TEST-SERVER------#################
{{- if .Values.saas.isSaasService }} 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ printf "%s-%s" $.Release.Name "test"  }}
    namespace: {{ $.Release.Namespace }}
    labels:
        app: {{ printf "%s-%s" $.Release.Name "test"  }}
        app.kubernetes.io/part-of: oneuptime
        app.kubernetes.io/managed-by: Helm
spec:
    selector:
        matchLabels:
            app: {{ printf "%s-%s" $.Release.Name "test"  }}
    replicas: 1
    template:
        metadata:
            labels:
                app: {{ printf "%s-%s" $.Release.Name "test"  }}
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository "HttpTestServer" .Values.image.tag }}
                  name: {{ printf "%s-%s" $.Release.Name "test"  }}
                  imagePullPolicy: {{ $.Values.image.pullPolicy }}
                  resources:
                    requests:
                      cpu: 250m
                    limits:
                      cpu: 500m
                  env:
                    - name: NODE_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: spec.nodeName
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: POD_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.namespace
                    - name: POD_IP
                      valueFrom:
                        fieldRef:
                          fieldPath: status.podIP
                    - name: POD_SERVICE_ACCOUNT
                      valueFrom:
                        fieldRef:
                          fieldPath: spec.serviceAccountName
                    - name: ONEUPTIME_HOST
                      value: {{ $.Values.oneuptime.hosts.host1.host }}
                    {{- if .Values.saas.isSaasService }}
                    - name: IS_SAAS_SERVICE
                      value: 'true'
                    {{- end }}
                    - name: NODE_ENV
                      value: {{ $.Values.nodeEnv }}
                  ports:
                      - containerPort: {{ $.Values.host.httpTestServerPort }}
                        hostPort: {{ $.Values.host.httpTestServerPort }}
                        name: {{ printf "%s-%s" $.Release.Name "test"  }}
            restartPolicy: {{ $.Values.image.restartPolicy }}
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ printf "%s-%s" $.Release.Name "test"  }}
        app.kubernetes.io/part-of: oneuptime
        app.kubernetes.io/managed-by: Helm
    name: {{ printf "%s-%s" $.Release.Name "test"  }}
    namespace: {{ $.Release.Namespace }}
spec:
    ports:
        - port: {{ $.Values.host.httpTestServerServicePort }}
          targetPort: {{ $.Values.host.httpTestServerPort }}
    selector:
        app: {{ printf "%s-%s" $.Release.Name "test"  }}
    type: ClusterIP
---
{{- end }}
########################################


{{- if .Values.autoScaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" $.Release.Name "test"  }}
spec:
  maxReplicas: {{ $.Values.autoScaler.maxReplicas }}
  minReplicas: {{ $.Values.autoScaler.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" $.Release.Name "test"  }}
  targetCPUUtilizationPercentage: {{ $.Values.autoScaler.averageCpuUtilization }}
---
{{- end }}