apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Release.Name "mongo-standalone"  }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ printf "%s-%s" $.Release.Name "mongo-standalone"  }}
    app.kubernetes.io/part-of: oneuptime
    app.kubernetes.io/managed-by: Helm
    name: {{ printf "%s-%s" $.Release.Name "mongo-standalone" }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  type: LoadBalancer
  selector:
    role: {{ printf "%s-%s" $.Release.Name "mongo-standalone" }}
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-%s" $.Release.Name "mongo-standalone" }}
spec:
  serviceName: {{ printf "%s-%s" $.Release.Name "mongo-standalone" }}
  replicas: 1
  selector:
    matchLabels:
      role: {{ printf "%s-%s" $.Release.Name "mongo-standalone" }}
  template:
    metadata:
      labels:
        role: {{ printf "%s-%s" $.Release.Name "mongo-standalone" }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ printf "%s-%s" $.Release.Name "mongo-standalone" }}
          image: mongo:latest
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--auth"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-standalone-persistent-storage-claim
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-standalone-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "gp2"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1000Gi