#######------SCRIPT RUNNER--------##########

# OneUptime Script Runner Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ printf "%s-%s" $.Release.Name "script"  }}
    namespace: {{ $.Release.Namespace }}
    labels:
        app: {{ printf "%s-%s" $.Release.Name "script"  }}
        app.kubernetes.io/part-of: oneuptime
        app.kubernetes.io/managed-by: Helm
spec:
    selector:
        matchLabels:
            app: {{ printf "%s-%s" $.Release.Name "script"  }}
    replicas: 1
    template:
        metadata:
            labels:
                app: {{ printf "%s-%s" $.Release.Name "script"  }}
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository "ScriptRunner" .Values.image.tag }}
                  name: {{ printf "%s-%s" $.Release.Name "script"  }}
                  imagePullPolicy: {{ $.Values.image.pullPolicy }}
                  resources:
                    requests:
                      cpu: 250m
                    limits:
                      cpu: 500m
                  env:
                      - name: NODE_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.nodeName
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_IP
                        valueFrom:
                          fieldRef:
                            fieldPath: status.podIP
                      - name: POD_SERVICE_ACCOUNT
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.serviceAccountName
                      - name: NODE_ENV
                        value: {{ $.Values.nodeEnv }}
                      - name: SERVER_URL
                        value: {{ template "oneuptime.serverUrl" $ }}
                      - name: IS_SAAS_SERVICE
                        value: 'true'
                      - name: CLUSTER_KEY
                        valueFrom:
                          configMapKeyRef:
                            name: {{ printf "%s-%s" $.Release.Name "configmap"  }}
                            key: clusterkey
                  ports:
                      - containerPort: {{ $.Values.host.scriptRunnerPort }}
                        hostPort: {{ $.Values.host.scriptRunnerPort }}
                        name: {{ printf "%s-%s" $.Release.Name "script"  }}
            restartPolicy: {{ $.Values.image.restartPolicy }}
---
# OneUptime Script Runner Deployment
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ printf "%s-%s" $.Release.Name "script"  }}
        app.kubernetes.io/part-of: oneuptime
        app.kubernetes.io/managed-by: Helm
    name: {{ printf "%s-%s" $.Release.Name "script"  }}
    namespace: {{ $.Release.Namespace }}
spec:
    ports:
        - port: {{ $.Values.host.scripRunnerServicePort }}
          targetPort: {{ $.Values.host.scriptRunnerPort }}
    selector:
        app: {{ printf "%s-%s" $.Release.Name "script"  }}
    type: ClusterIP
---
###################################


{{- if .Values.autoScaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" $.Release.Name "script"  }}
spec:
  maxReplicas: {{ $.Values.autoScaler.maxReplicas }}
  minReplicas: {{ $.Values.autoScaler.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" $.Release.Name "script"  }}
  targetCPUUtilizationPercentage: {{ $.Values.autoScaler.averageCpuUtilization }}
---
{{- end }}