
version: '3.7'

x-common-variables: &common-variables
   IS_SAAS_SERVICE: ${IS_SAAS_SERVICE}


services:
    
    postgres:
        image: postgres:latest
        restart: always
        env_file:
            - ./Postgres/.env
        ports:
            - '5400:5432'
        volumes: 
            - postgres:/var/lib/postgresql/data

    saml:
        image: kenchan0130/simplesamlphp
        ports:
            - 9876:8080
            - 8443:8443
        env_file:
            - ./SAML/.env
        volumes:
            - ./SAML/users.php:/var/www/simplesamlphp/config/authsources.php

    redis:
        image: redis:7.0.3
        ports:
            - '6379:6379'
        command: redis-server
        env_file:
            - ./Redis/.env
        
    dashboard-api:
        ports:
            - '3002:3002'
        image: oneuptime/dashboard-api:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./DashboardAPI/.env
        environment: *common-variables
        depends_on:
            - redis
            - haraka

    identity:
        ports:
            - '3087:3087'
        image: oneuptime/identity:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Identity/.env
        environment: *common-variables
        depends_on:
            - redis
            - postgres
            - mail
            
    alert:
        ports:
            - '3088:3088'
        image: oneuptime/alert:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Alert/.env
        environment: *common-variables
        depends_on:
            - redis
            - postgres
    
    integration:
        ports:
            - '3089:3089'
        image: oneuptime/integration:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Integration/.env
        environment: *common-variables
        depends_on:
            - redis
            - postgres

    accounts:
        ports:
            - '3003:3003'
        image: oneuptime/accounts:latest
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./Accounts/.env
        environment: *common-variables
        depends_on:
            - identity
        
    dashboard:
        ports:
            - '3000:3000'
        image: oneuptime/dashboard:latest
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./Dashboard/.env
        environment: *common-variables
        depends_on:
            - dashboard-api
            - accounts
    home:
        ports:
            - '1444:1444'
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./Home/.env
        environment: *common-variables
        image: oneuptime/home:latest
    
    status-page:
        ports:
            - '3006:3006'
        image: oneuptime/status-page:latest
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./StatusPage/.env
        environment: *common-variables
        depends_on:
            - dashboard-api
            - accounts
            - dashboard
            
    admin-dashboard:
        ports:
            - '3100:3100'
        image: oneuptime/admin-dashboard:latest
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./AdminDashboard/.env
        environment: *common-variables
        depends_on:
            - dashboard-api
            - accounts
            
    http-test-server:
        ports:
            - '3010:3010'
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./HttpTestServer/.env
        environment: *common-variables
        image: oneuptime/http-test-server:latest
    
    licensing:
        ports:
            - '3004:3004'
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Licensing/.env
        environment: *common-variables
        image: oneuptime/licensing:latest
    
   
    realtime:
        ports:
            - '3300:3300'
        image: oneuptime/realtime:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Realtime/.env
        environment: *common-variables

            
    helmchart:
        ports:
            - '3423:3423'
        image: oneuptime/helmchart:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./HelmChart/.env
        environment: *common-variables

               
    probe-api:
        ports:
            - '3400:3400'
        image: oneuptime/probe-api:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./ProbeAPI/.env
        environment: *common-variables
            
    probe1:
        image: oneuptime/probe:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Probe/.env
        environment: 
            <<: *common-variables
            PROBE_NAME: Probe 1
            PROBE_KEY: test-key
        depends_on:
            - dashboard-api
            
    probe2:
        image: oneuptime/probe:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Probe/.env
        environment: 
            <<: *common-variables
            PROBE_NAME: Probe 2
            PROBE_KEY: test-key
        depends_on:
            - dashboard-api
            
    api-docs:
        ports:
            - '1445:1445'
        image: oneuptime/api-docs:latest
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./ApiDocs/.env
        environment: *common-variables
   
    haraka:
        ports:
            - '2525:2525'
        image: oneuptime/haraka:latest
        env_file:
            - ./Haraka/.env
        
    
           
    mail:
        ports:
            - '3009:3009'
        image: oneuptime/mail:latest
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Mail/.env
        environment: *common-variables
        depends_on:
            - haraka
            - postgres
            
    nginx:
        depends_on:
            - dashboard-api
            - home
            - dashboard
            - accounts
            - admin-dashboard
        restart: always
        image: oneuptime/nginx:latest
        ports:
            - '80:80'
            - '443:443'

volumes:
    postgres:
