# This docker file is for CI.
# It it builds and tests docker containers in the CI pipeline.

version: '3.7'

x-common-variables: &common-variables
   IS_SAAS_SERVICE: ${IS_SAAS_SERVICE}

services:
    postgres:
        image: postgres:latest
        restart: always
        env_file:
            - ./Postgres/.env
        ports:
            - '5400:5432'
        volumes:
            - postgres:/var/lib/postgresql/data
            
    saml:
        image: kenchan0130/simplesamlphp
        ports:
            - 9876:8080
            - 8443:8443
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./SAML/.env
        volumes:
            - ./saml/users.php:/var/www/simplesamlphp/config/authsources.php

    redis:
        image: redis:7.0.3
        ports:
            - '6379:6379'
        command: redis-server
        env_file:
            - ./Redis/.env

    dashboard-api:
        ports:
            - '3002:3002'
        build:
            context: .
            dockerfile: ./DashboardAPI/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./DashboardAPI/.env
        environment: *common-variables
        depends_on:
            - redis
            - postgres
    
    file:
        ports:
            - '3125:3125'
        build:
            context: .
            dockerfile: ./File/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./File/.env
        environment: *common-variables
        depends_on:
            - redis
            - postgres
            
    identity:
        ports:
            - '3087:3087'
        build:
            context: .
            dockerfile: ./Identity/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Identity/.env
        environment: *common-variables
        depends_on:
            - redis
            - postgres
            - mail
    
    alert:
        ports:
            - '3088:3088'
        build:
            context: .
            dockerfile: ./Alert/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Alert/.env
        environment: *common-variables
        depends_on:
            - redis
            - postgres
    
    integration:
        ports:
            - '3089:3089'
        build:
            context: .
            dockerfile: ./Integration/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Integration/.env
        environment: *common-variables
        depends_on:
            - redis
            - postgres
            
    accounts:
        ports:
            - '3003:3003'
        build:
            context: .
            dockerfile: ./Accounts/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./Accounts/.env
        environment: *common-variables
        depends_on:
            - identity
            
    dashboard:
        ports:
            - '3009:3009'
        build:
            context: .
            dockerfile: ./Dashboard/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./Dashboard/.env
        environment: *common-variables
        depends_on:
            - dashboard-api
            - accounts

    status-page:
        ports:
            - '3105:3105'
        build:
            context: .
            dockerfile: ./StatusPage/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./Dashboard/.env
        environment: *common-variables
        depends_on:
            - dashboard-api


    home:
        ports:
            - '1444:1444'
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./Home/.env
        environment: *common-variables
        build:
            context: .
            dockerfile: ./Home/Dockerfile
            
    admin-dashboard:
        ports:
            - '3100:3100'
        build:
            context: .
            dockerfile: ./AdminDashboard/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./AdminDashboard/.env
        environment: *common-variables
        depends_on:
            - dashboard-api
            - accounts
            
    http-test-server:
        ports:
            - '3010:3010'
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./HttpTestServer/.env
        environment: *common-variables
        build:
            context: .
            dockerfile: ./HttpTestServer/Dockerfile

    licensing:
        ports:
            - '3004:3004'
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Licensing/.env
        environment: *common-variables
        build:
            context: .
            dockerfile: ./Licensing/Dockerfile
            
    realtime:
        ports:
            - '3300:3300'
        build:
            context: .
            dockerfile: ./Realtime/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Realtime/.env
        environment: *common-variables

    helmchart:
        ports:
            - '3423:3423'
        build:
            context: .
            dockerfile: ./HelmChart/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./HelmChart/.env
        environment: *common-variables

    probe-api:
        ports:
            - '3400:3400'
        build:
            context: .
            dockerfile: ./ProbeAPI/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./ProbeAPI/.env
        environment: *common-variables


    probe1:
        build:
            context: .
            dockerfile: ./Probe/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Probe/.env
        environment: 
            <<: *common-variables
            PROBE_NAME: Probe 1
            PROBE_KEY: test-key
        depends_on:
            - dashboard-api
            
    probe2:
        build:
            context: .
            dockerfile: ./Probe/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Probe/.env
        environment: 
            <<: *common-variables
            PROBE_NAME: Probe 2
            PROBE_KEY: test-key
        depends_on:
            - dashboard-api
            
    api-docs:
        ports:
            - '1445:1445'
        build:
            context: .
            dockerfile: ./ApiDocs/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonUI/.env
            - ./ApiDocs/.env
        environment: *common-variables
   
    haraka:
        ports:
            - '2525:2525'
        build:
            context: ./Haraka
            args:
                PORT: '2525'
        env_file:
            - ./Haraka/.env
        
            
    mail:
        ports:
            - 3190:3190
        build:
            context: .
            dockerfile: ./Mail/Dockerfile
        env_file:
            - ./Common/.env
            - ./CommonServer/.env
            - ./Mail/.env
        environment: *common-variables
        depends_on:
            - haraka
            - postgres
        
    nginx:
        depends_on:
            - dashboard-api
            - home
            - dashboard
            - accounts
            - admin-dashboard
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./Nginx
        ports:
            - '80:80'
            - '443:443'

volumes:
    postgres:
