##################################################################################
## Important: If you're implenting this in the enterprise environment, this should always be `false`.
## Is this OneUptime SaaS service. This will deploy all the SaaS env vars
##

mongodb:
    image:
        registry: docker.io
        repository: mongo
        tag: latest
        pullPolicy: Always
    replicaSet:
        enabled: true
        name: rs0
        useHostnames: true
        key: mongodboneuptime
        secondary: 0
        arbiter: 0
    persistence:
        enabled: true
        mountPath: /bitnami/mongodb
        size: 1000Gi
        storageClass: nfs-client

saas:
    isSaasService: true
    exposeInitScriptContainer: true
    slackErrorLog:
        webhook: https://hooks.slack.com/services/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
        channel: oneuptime-engineering
    stripe:
        publicKey: pk_test_UynUDrFmbBmFVgJXd9EZCvBj00QAVpdwPv
        privateKey: sk_test_YxwnzywggtAd8jDaHecNmHiN
    airtable:
        key: keye3gzJRafDIhRKg
        baseId: appgek0ngJaHhppeJ
    amplitude:
        key: 4b76c47248f969446af69dfdbf687d90
    licensing:
        airtable:
            key: keye3gzJRafDIhRKg
            baseId: appksCeuKfCS0e8fR
        tokenSecret: LicenseTokenSecret

httpTestServer:
    hosts:
        host1:
            host: arm-test-server.oneuptime.com
            tls:
                enabled: false
                crt:
                key:
oneuptime:
    hosts:
        host1:
            host: arm.oneuptime.com
            tls:
                enabled: false
                crt:
                key:
    licensingUrl: https://oneuptime.com/license

image:
    registry: docker.io
    repository: oneuptimeproject
    tag: latest-arm64
    pullPolicy: Always
    restartPolicy: Always

replicaCount: 1

# This should be 32 chars in length.
encryptionKey: pg#K^C$-)IGOg6DYXDGq2jdmfws0MiR7

# Is backend on HTTPS?
backendProtocol: 'https'

# domain for staging status page
# Status page CNAME to display to customers
# To be shown on the cusom domain tab of status page.
statusPageDomain: 'arm-statuspage.oneuptime.com'

haraka:
    fromEmail: 'noreply@oneuptimeapp.com'
    fromName: 'OneUptime Staging'
    domain: 'oneuptimeapp.com'
    user: 'noreply@oneuptimeapp.com'
    password: 'tX8z_bDEcRdRHnyKxAHYEQk_B'
    dkimPrivateKey: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBd0U0R1hxai9lODQ4VW1mNkttN0xsQUliZnpFTG5VbmdHQVc0NXBhYzhKelZoNzRNCmloVWZPZnB5cGNJVXZHSnFOaHRuSHJnRHE1Wk9QQTlNc2pFM1drYXQyZ2dUV0V2RFhDY3d0eHZVWnU3blpudkIKK3cxMzVRajNQeGZGVE1Tb1c4VWR5cHQ3UXlpRUhpVXVPZGNrVFhKM2sra1U5Qk41OVgxNmhPQlJtN2JkcnNNagpNQlEvNUQ3VHRjMGJ5TjBnd2dBUit6OXhueFFQWWpwNEtmaE1XWUxXRjFLTHdPQUZoZ1E4eFp3ZFZjTkY4aWl3CmF3a3FIYWx5VFg4SnFZNFRBamVXYW1icXdvQlN4V09nT2w4d1pSS2pPZFNhRmdEdHRRVDBrMzE2QzZxVEw1NlEKbStUMThac3k4MkFYdEQydGhCMG44T3lrSjhnV1kzMVVaSjZRbndJREFRQUJBb0lCQVFDSVVBWjEzUWRVUkFsQQpSSkh3dUI2NEtKSkRJNG5mRVhtMnJYKzJlL1o5SEQ3RC9MUTR3T1lrbStIZW0yZEZiZUZwdnh6bWludVhpbkNrClpCZnlpNjUzNEhmbGdDbnVRYTRXU1hWZnBtdDJGMHlSdVpIMEdrVHRaZUNVcVkzaWI5Z0RUUU5rRmJoWEQ0WXYKTkIzRFJEeG9aWVpib3pHR0hiUXFqcXBsTy9pOURiVWNlWmRoVlpEdlhFb21OTjBxYkNCZFhyN3lQcDBySXJqVwpjVXFxS1JSU1cyOU8vWndKeGt3Q1pwRTEvRHZDMjNpOUFpZWU1M1RMMTE4YTA5SDhrSmQ4YjBMYlpTZWhqWGVOCjB0c0h3dzhwNVY1eW93RjlnN3NmM0hhalRzSUd2eG5mWUNVMS9Dby9HQ3FyeW1IKzNLK3VOY0YwNHJ6aGluZmQKVDNHMWo0azVBb0dCQU9Cb0c1aWVZSkYyQkQ0elJnRVV5REFiS3pscGtqclN0YWh5eThxbnd5S2FLcjRVbzh5YQpPUFE3UVFuSnR1TkwwN1NVM211RmJKa2prTXNFbWYvTkdNSWlQOWd6cEdYeHZpcTlIM2t3SnlNZTVMYm5rYzZRCkpPSE5zKzBQN1FzZWlVUVZHSHBhc2FQR01hcXZ1dnIzMzNUYks3OEJIWXc2ak5SZU1qbFV2bm5sQW9HQkFOdGcKN1BkTHZQdGg3WDN0UTcxRjl4YjNCR1FBUmdIWTUvNWVZUFNjWGxCOFBkWk1abG95dkZuaGVpcjVUdlpMajhMSQpKTEw3NmJxYWF4OGJ4MmNueFJydUxtYnl2YmdGeUN4cFpVNUVhc1J2RDNhcTY1T0padGRacGtRcEdTUWgxWFl4CnB2R3Q3TGpWS1c3WlhYbGxwR3RVMjdNVjE4SHhDWlp2V0dSVkZxZ3pBb0dBRHcxc3JIUVRMaTZvWWpPMlFtUk8KZVV1WlBxU2lObWZqMzRTenZzZzZBcHdzdWN0UW9XekczVHNNUmNmT0NMa1JYaytPQzlCTFZJcGFNQVFEQUhHVgpjNUF3a0NRR3B2L3NMWm01L3JzSUpRYnhlSU5YK0c4YXlqcXVFdnk2ZmNCeW5LcDlsZGQzaXZERWJCcVZoRGdVCk9SWnFmTWxxWGZtZmNLOVExeCtrRnpFQ2dZRUFucHdpVjkyYmdnallZMzVpeG5yS1hnRTBYSFRTS00zQlZlaTQKb3NKWGNrdVJqZG5vK25mS05CWFFkVGVSUG9OOUtpLzRVS3ZQM2dsOVA1MmUrdGNITENSZXlqSGd0eWIvQmhVaAptSWZneGFzaWZBS3hsaGIya3VhUFRxS0VPZHA0Y2g4Tis1aHJHV3VNckVkZHpNS1BNTWJHbldGQ2dFY2NUbmFzCmFzWVdQbjhDZ1lFQWswVVNzWWtwekpRSGV1TTBVaHpnZkQyTXZmQm9LMjV6OFMvWkRlSnJUVFUwTjBQUTBVdi8KNTNvd0Yxd3Q2NWFjZjRJUFg3VElsZ3lZc2dFcVpFZWRDUU90a05LbkNjRFNVVnVLcWNqQW9MdUJzeThrZkVFUwphaFY0dzBkdFhaUnRJeWErRExaYlkwU0lGaWU5dVdTN0FqTnJONjJBUGVrWlhxcHlmblZ3ZDE4PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo='

# Push notifications.
# Generate public and pivate key for push notifications.
# These are just the test keys.
# You can generate them by:
# First install the web-push npm package using npm install web-push -g, then run web-push generate-vapid-keys

pushNotification:
    publicKey: 'BFAPbOTTU14VbTe_dnoYlVnOPLKUNm8GYmC50n3i4Ps64sk1Xqx8e894Clrscn1L2PsQ8-l4SsJVw7NRg4cx69Y'
    privateKey: '8aXTsH48-cegK-xBApLxxOezCOZIjaWpg81Dny2zbio'
    url: 'mailto:support@oneuptime.com'

statusPage:
    # base64 encoded version of the certificate and private key files
    cert: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZBakNDQStxZ0F3SUJBZ0lKQU1pUWhGTDUydDBUTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdYTVFzd0NRWUQKVlFRR0V3SlZVekVQTUEwR0ExVUVDQXdHUW05emRHOXVNUll3RkFZRFZRUUhEQTFOWVhOellXTm9kWE5sZEhSegpNUll3RkFZRFZRUUtEQTFJWVdOclpYSmlZWGtnU1c1ak1SRXdEd1lEVlFRTERBaFRiMlowZDJGeVpURVNNQkFHCkExVUVBd3dKWm5scGNHVXVZMjl0TVNBd0hnWUpLb1pJaHZjTkFRa0JGaEZxZFdSbFFHaGhZMnRsY21KaGVTNXAKYnpBZUZ3MHlNVEF6TVRBeU1qQXdNRGhhRncweU16QTJNVE15TWpBd01EaGFNSUdYTVFzd0NRWURWUVFHRXdKVgpVekVQTUEwR0ExVUVDQXdHUW05emRHOXVNUll3RkFZRFZRUUhEQTFOWVhOellXTm9kWE5sZEhSek1SWXdGQVlEClZRUUtEQTFJWVdOclpYSmlZWGtnU1c1ak1SRXdEd1lEVlFRTERBaFRiMlowZDJGeVpURVNNQkFHQTFVRUF3d0oKWm5scGNHVXVZMjl0TVNBd0hnWUpLb1pJaHZjTkFRa0JGaEZxZFdSbFFHaGhZMnRsY21KaGVTNXBiekNDQVNJdwpEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzd1TjAzc0labXpVdVcwY0JlSDB6eWVyWWFOCnEra3lIYmJtMmt3N2VjUkVlZ2JGZTVBU25uMi9Eb1lJMEV0cEhNeHVCeXovMG9KOS83ZmJUUTEvSEphMmVRRngKRFQwTW5CS1MrdURYbHBzbUJrSUFNN2R3eTZQTldjeWU5MC9yTWc3Zkx2MzRZbHJxUVF5Z0NwaGF6MUk5SGdKRAplNjhoQXpvbXJVQnZqYWJMRDZWWmdFRzI5Qit6M1I3TktSTlRrQzdpdzdPeHltMjA1WjRDa3FqRUI2YXEvR2cxCmNoclBFeEpHdUlEc2xTNm94NVBrOS9yWkx6REc3RkZ6b2syK1Rrb1ZGU3I0RHVLcHp4WEZXVmRMRWF2RlU1dngKYm8rb2t6dzVyRGd0Z0JWek1ncEJaWkxGSXVXL21OS2VKa1V0WUZBdjBkN3dtYUhqemxsZDREYUdjU0VDQXdFQQpBYU9DQVUwd2dnRkpNSUcyQmdOVkhTTUVnYTR3Z2F1aGdaMmtnWm93Z1pjeEN6QUpCZ05WQkFZVEFsVlRNUTh3CkRRWURWUVFJREFaQ2IzTjBiMjR4RmpBVUJnTlZCQWNNRFUxaGMzTmhZMmgxYzJWMGRITXhGakFVQmdOVkJBb00KRFVoaFkydGxjbUpoZVNCSmJtTXhFVEFQQmdOVkJBc01DRk52Wm5SM1lYSmxNUkl3RUFZRFZRUUREQWxtZVdsdwpaUzVqYjIweElEQWVCZ2txaGtpRzl3MEJDUUVXRVdwMVpHVkFhR0ZqYTJWeVltRjVMbWx2Z2drQWh3Ti95cEM5CnRFVXdDUVlEVlIwVEJBSXdBREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0N3WUQKVlIwUEJBUURBZ1R3TUZjR0ExVWRFUVJRTUU2Q0NXWjVhWEJsTG1OdmJZSUxLaTVtZVdsd1pTNWpiMjJDQ1d4dgpZMkZzYUc5emRJSUxLaTVzYjJOaGJHaHZjM1NDREdaNWFYQmxZWEJ3TG1OdmJZSU9LaTVtZVdsd1pXRndjQzVqCmIyMHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBREJ3N1JJRVkxNzQ0aE9lUlVwbFdORDBwWGs4dE9SblRTWUgKNHJrZkR2MWtYandvL0pQY3IxcDNPU3A5VVMrTWlyWmxNL240dHVVdW9BNzA3Q2FxOXpuVFphT3ZEZEdWbDF3MwoyelRtbVlIbmk1OGFyK2NwdVN1Z1M2UnpWRlM5OVNQSHNwbVFyRjl4VkY5K3preWsvdHltRHE0MHFJZHJhTm5QCnJWWFB6cG5YUGxUUHZENTFFN2toenFZNDVVNWNtRUNMbmN2T3Z1Y3VlNys5M0V1anhYaE05RTZvT2w2Z2txQW0KSnNPdDdnQWxqd0Y1Vkx1YWVCYWJvWENYUmVBaW9ZZFk2YitCL0tyb21zTTZ6ejZzWnE5N3JRZFg2RkZVMWhlZwpHcGhOQm5vV28zNk1TMVRkbnhXYW5jcTVtcWhIMElzaStwM2pJOU1JeGZYRWw5MHNsMzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K'
    key: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcnU0M1Rld2htYk5TNWJSd0Y0ZlRQSjZ0aG8ycjZUSWR0dWJhVER0NXhFUjZCc1Y3CmtCS2VmYjhPaGdqUVMya2N6RzRITFAvU2duMy90OXRORFg4Y2xyWjVBWEVOUFF5Y0VwTDY0TmVXbXlZR1FnQXoKdDNETG84MVp6SjczVCtzeUR0OHUvZmhpV3VwQkRLQUttRnJQVWowZUFrTjdyeUVET2lhdFFHK05wc3NQcFZtQQpRYmIwSDdQZEhzMHBFMU9RTHVMRHM3SEtiYlRsbmdLU3FNUUhwcXI4YURWeUdzOFRFa2E0Z095VkxxakhrK1QzCit0a3ZNTWJzVVhPaVRiNU9TaFVWS3ZnTzRxblBGY1ZaVjBzUnE4VlRtL0Z1ajZpVFBEbXNPQzJBRlhNeUNrRmwKa3NVaTViK1kwcDRtUlMxZ1VDL1IzdkNab2VQT1dWM2dOb1p4SVFJREFRQUJBb0lCQUFFdUJoMTJiRHVYSkFYOAprNHoxRTQyakhGUjkvQnpVZzdMS0Y4clAwK0JvL2RHeDMwVjNlcTRxYmJTbHRwSHJvWkFYWmVEOTBMT2ttZWJwCmlibC9rL2ZJUDBTdE9JT2k1Q0tUN3pFNUF3RUUzcUh2VW1uNFRzZEtDVU1DQjNUNGh4dm1rWENSRGtqQ3I3R2cKR3JJd1dwbVpZK3hyL0JlUVIyOUs5M3dweEhETmh1MlZub3IrbzFWQXJMUjJ2VVNjMGVDWFZpazhEQ0Q3NTlTZwpZN1EvSzRyZ1FINE5qTXQvNVNROTh2RzZDOFNnditlUmU4RThVdmhIU2NBT0h3bWxzMW1YU2tvL2swdEpxaWd1Ck1RazVsWnIrVHdjWlcrMWs1M1dkcDdXRUJzNElMQmMvbUFkTytCcGZ1bnB6SFBIc0tGYzdHY0FpQmZOMHFZZWUKN004NWg0a0NnWUVBNkRxb2ZYbmRJblpyUWlXWHo0RVN0NUVwVm9NUXMwUVNEd2Q1NmdldEcyMGpySXBCTEdMNAp3Q3ByV0xGN1F4OHVxOHpwS2tBbjVKbUEvTlI4OERmQ2d3WXluYm5CTjNNUjB6ZG1welFkZHNBc2VxbkJ5RVhICkxLVUQ3TDNvNVNzcEttZzBMVit1TGhzZkp3cWgveGZlS3NGSkV3eEp2U0ZkcUE1ZVp1TGlSL3NDZ1lFQXdOWWEKV1UySnM1dGc5S3JDMDVOY1hRTDFPZVFPV0plcFVSRXhsdUtjUWVyZzMxUVZYOEMwWEJmZ2VxUUNhTlpxdmNQYwo2MjR4d0dWUVdCODF4ZW1Kc2pENjNIemdPbzVRZkltYllvdzdCbEJzMFM0eWg3d1QzK3NnSVVMUnZhSG5mMGZoCm5zV2YvQjlKRXJFTjRSTXZ4OTMrZ0xiN1g3TWpIZ1U3ZGNQT2xKTUNnWUE2eE1WbzQ1TVRxcFlnS2pWTjNPTW8KczBLYjB4VkIySU1kYkkzc3JMNmhCekNVOUhQajBMUVVwV2QvRFlNZERHSWFOZ1Azbmo2Nk9pS0xXUmE1RDlOWQpweFBlR0drT0tEK2xqUXFjVzdMdEgxcmlPOTEvV2pFNldoUXhNQ29rL0pReFdDZUVLQWVEUVhmVHdId1lleWpNCjl4Y1FDL2NKTnMxbHZ5VWlzbDREU3dLQmdRQ0V5eXdMOFd4eFpmL0huVXhiUFBCdkVObGt5MXJod1ZjVS8zMGgKeGQ0TE9yOHVyQTJvQ2VGcVJmc05HYUtiSllVT056SU1ZcThhS2VyQk5JVG9US0hKTnhlWi9OakJHajNzOVNvdgpIQmlOaVpiV0dqVXI2ZVhaM21ZYTRaUGtQZmxZV2x6UjVJLytwR0RDNFhDSVhaa2F6eEl5KzA5eUlMOS9MZVU3CmZPTG14d0tCZ1FEWmFpTmdlTzk0cG9vZ092UkI1RkVKblFmcGwvMGdvbDNSYXUvQU0yTW93NTdmUjlNb1I0cFUKVFFDV0NwRy8vZHlZYXBTU201MnBNYTlEWEE1a2ZEOW1MclVHWk96S0drUW9Ka2h3dnJYbi9qY0NKY0JBYnBHagpJT01sK3QxMHdBL2xOZ3UwbEhJMHVKTFBOaHFEQ1ZHU21kVTVVWDUrdjFEenk1UklzbFFwSmc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo='

nginx-ingress-controller:
    service:
        type: NodePort
    hostNetwork: true

redis:
    redisPort: 6379
    image:
        registry: docker.io
        repository: redis
        tag: latest
        pullPolicy: Always
    usePassword: false
    persistence:
        enabled: true
        mountPath: /bitnami/mongodb
        size: 2Gi
        storageClass: nfs-client
