name: Compile Status Page

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   
      - 'release'
      - 'staging-release'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd CommonUI && npm install --force
      - run: cd StatusPage && npm install && npm run compile
  